#Inserimento informazioni prese da GECO
WITH GECO_CORE AS(
select DISTINCT
   cast(off.ID_OFFERTA as string) as ID_OFFERTA
  , cast(off_dett.ID_DETTAGLIO as string) as ID_DETTAGLIO
  , 'S' as FLG_PUBBLICATO_S_N
  , off.COD_OFFERTA
  , REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CAST(off.COD_offerta AS STRING),'_02A', ''), '_02B', ''), '_02C', ''), '_02D', ''), '_02E', ''), '_01A', ''), '_01B', ''), '_01C', ''), '_01D', ''), '_01E', ''), '_02', ''), '_01', '') as COD_OPPORTUNITY_CORRETTO
  , COALESCE(off.POD_PDR, 'ND') AS PDP
  , COALESCE(OFF.NUM_POD_PDR, 0) AS NUMERO_PDP
  , COALESCE(off.CODICE_REMI, 'ND') AS CABINA_REMI
  , CASE WHEN off.ENE_VERDE IS NULL AND off.FLAG_EV_PPA IS NULL THEN 'ND' 
         ELSE CASE WHEN off.ENE_VERDE='Y' or off.FLAG_EV_PPA='S' THEN 'S' else off.ENE_VERDE END END AS FLG_ENVE_S_N_I
  , COALESCE(off.CASE_ADDENDUM_VERDE) AS CASE_ADDENDUM_ENVE
  , COALESCE(TIMESTAMP(off_dett.DATA_COPERTURA), TIMESTAMP(off.data_copertura_extra_sys), TIMESTAMP(lsp.rec_date)) AS DATA_COPERTURA
  , CASE WHEN off.VETTORE='ELE' THEN 'E' ELSE
        CASE WHEN off.VETTORE='GAS' THEN 'G' ELSE 'ND' END END AS COMMODITY_G_E
  , DATE(off.DATA_CARICAMENTO) AS DATA_CARICAMENTO
  , DATE(off.DATA_INIZIO_OFFERTA) AS DATA_INIZIO_OFFERTA
  , DATE(off.DATA_FINE_OFFERTA) AS DATA_FINE_OFFERTA
  , DATE(off.DATA_INIZIO_COPERTURA) AS DATA_INIZIO_COPERTURA
  , DATE(off.DATA_FINE_COPERTURA) AS DATA_FINE_COPERTURA
  , off.COD_TIPO_CONTRATTO AS TIPO_CONTRATTO
  , CASE WHEN off.TIPO_COPERTURA = 'Listino Parti Fisse' THEN 'FIXING PARTI FISSE' ELSE TC.DESC_TIPO_CONTRATTO END AS DES_TIPO_CONTRATTO 
  , TC2.string_field_1 AS DES_TIPO_CONTRATTO_SINTESI
  , CASE WHEN off.VETTORE='ELE' OR off.TIPO_OFFERTA_ELE IS NOT NULL THEN off.TIPO_OFFERTA_ELE ELSE
        'ND' END AS PROFILO_MONO_BIO_POP_FASCE

  , COALESCE(OFF.COD_TENSIONE, TP.TENSIONE_DATA_DELIVERY, TP1.TENSIONE, 4.0) AS TENSIONE
  , tens.SIGLA AS DES_TENSIONE
  , tra.INDICE_TRANSCODIFICATO AS INDICE
  , off.TIPOLOGIA_USO AS TIPOLOGIA_USO #Staccare da Geco offerte e attaccare alla pratiche
  , UPPER(off.VENDITORE) AS VENDITORE
  , off.seller_code AS COD_VENDITORE
  , DATE(off_dett.DATA_VOLUME) AS DATA_DELIVERY
  , CASE WHEN off.VETTORE='GAS' then COALESCE(off_dett.SMC_COPERTI, off_dett.SMC_DA_COPRIRE, off_dett.smc) ELSE (COALESCE(off_dett.MWH_F1_COPERTI, MWH_F1_DA_COPRIRE, off_dett.mwh_f1) + COALESCE(off_dett.MWH_F2_COPERTI, MWH_F2_DA_COPRIRE, off_dett.mwh_f2) + COALESCE(off_dett.MWH_F3_COPERTI, MWH_F3_DA_COPRIRE, off_dett.mwh_f3)) END AS VOLUME_COPERTO_MC_MWH
  , CASE WHEN off.VETTORE='GAS' then 0 ELSE COALESCE(off_dett.MWH_F1_COPERTI, MWH_F1_DA_COPRIRE, off_dett.mwh_f1) END AS VOLUME_COPERTO_F1_MWH
  , CASE WHEN off.VETTORE='GAS' then 0 ELSE COALESCE(off_dett.MWH_F2_COPERTI, MWH_F2_DA_COPRIRE, off_dett.mwh_f2) END AS VOLUME_COPERTO_F2_MWH
  , CASE WHEN off.VETTORE='GAS' then 0 ELSE COALESCE(off_dett.MWH_F3_COPERTI, MWH_F3_DA_COPRIRE, off_dett.mwh_f3) END AS VOLUME_COPERTO_F3_MWH
  , 0 AS VOLUME_COPERTO_P_MWH #DA AGGIORNARE SE E QUANDO SI POTRANNO FARE LE COPERTURE PER POP
  , 0 AS VOLUME_COPERTO_OP_MWH #DA AGGIORNARE SE E QUANDO SI POTRANNO FARE LE COPERTURE PER POP

  , CASE WHEN off.VETTORE='GAS' then COALESCE(off_dett.SMC_COPERTI, off_dett.SMC_DA_COPRIRE, off_dett.smc) ELSE (COALESCE(off_dett.MWH_F1_COPERTI, MWH_F1_DA_COPRIRE, off_dett.mwh_f1) + COALESCE(off_dett.MWH_F2_COPERTI, MWH_F2_DA_COPRIRE, off_dett.mwh_f2) + COALESCE(off_dett.MWH_F3_COPERTI, MWH_F3_DA_COPRIRE, off_dett.mwh_f3))/tens.COEFF END AS VOLUME_NETTO_COPERTO_MC_MWH
  , CASE WHEN off.VETTORE='GAS' then 0 ELSE COALESCE(off_dett.MWH_F1_COPERTI, MWH_F1_DA_COPRIRE, off_dett.mwh_f1) /tens.COEFF END AS VOLUME_NETTO_COPERTO_F1_MWH
  , CASE WHEN off.VETTORE='GAS' then 0 ELSE COALESCE(off_dett.MWH_F2_COPERTI, MWH_F2_DA_COPRIRE, off_dett.mwh_f2) /tens.COEFF END AS VOLUME_NETTO_COPERTO_F2_MWH
  , CASE WHEN off.VETTORE='GAS' then 0 ELSE COALESCE(off_dett.MWH_F3_COPERTI, MWH_F3_DA_COPRIRE, off_dett.mwh_f3) /tens.COEFF END AS VOLUME_NETTO_COPERTO_F3_MWH
  , 0 AS VOLUME_NETTO_COPERTO_P_MWH
  , 0 AS VOLUME_NETTO_COPERTO_OP_MWH
  , CASE WHEN off.VETTORE='GAS' THEN 0 ELSE (COALESCE(off_dett.MWH_F1_COPERTI, MWH_F1_DA_COPRIRE, off_dett.mwh_f1) + COALESCE(off_dett.MWH_F2_COPERTI, MWH_F2_DA_COPRIRE, off_dett.mwh_f2) + COALESCE(off_dett.MWH_F3_COPERTI, MWH_F3_DA_COPRIRE, off_dett.mwh_f3)) -(COALESCE(off_dett.MWH_F1_COPERTI, MWH_F1_DA_COPRIRE, off_dett.mwh_f1) + COALESCE(off_dett.MWH_F2_COPERTI, MWH_F2_DA_COPRIRE, off_dett.mwh_f2) + COALESCE(off_dett.MWH_F3_COPERTI, MWH_F3_DA_COPRIRE, off_dett.mwh_f3))/tens.COEFF END VOLUME_PERDITE_MC_MWH
  , CASE WHEN off.VETTORE='GAS' THEN 0 ELSE COALESCE(off_dett.MWH_F1_COPERTI, MWH_F1_DA_COPRIRE, off_dett.mwh_f1)-COALESCE(off_dett.MWH_F1_COPERTI, MWH_F1_DA_COPRIRE, off_dett.mwh_f1)/tens.COEFF END VOLUME_PERDITE_F1_MWH
  , CASE WHEN off.VETTORE='GAS' THEN 0 ELSE COALESCE(off_dett.MWH_F2_COPERTI, MWH_F2_DA_COPRIRE, off_dett.mwh_f2)-COALESCE(off_dett.MWH_F2_COPERTI, MWH_F2_DA_COPRIRE, off_dett.mwh_f2)/tens.COEFF END VOLUME_PERDITE_F2_MWH
  , CASE WHEN off.VETTORE='GAS' THEN 0 ELSE COALESCE(off_dett.MWH_F3_COPERTI, MWH_F3_DA_COPRIRE, off_dett.mwh_f3)-COALESCE(off_dett.MWH_F3_COPERTI, MWH_F3_DA_COPRIRE, off_dett.mwh_f3)/tens.COEFF END VOLUME_PERDITE_F3_MWH
  , 0 AS VOLUME_PERDITE_P_MWH
  , 0 AS VOLUME_PERDITE_OP_MWH
  , 0 AS VOLUME_ENVE_MWH

  , COALESCE(
    case 
        when lsp.id is null then gtl.cod_listino_margini 
        when lsp.id is not null and (lsp.baseload is not null or lsp.f1 is not null or lsp.peak is not null or lsp.p_gas is not null) THEN 'SPE'
    end, 'STD') AS FLG_LISTINO_MP_STD_GC10_SPE

  , OFF.SISTEMA
  , OFF.CONTRATTO_OLD
  , OFF.COD_TIPO_CONTRATTO_OLD
  , TC1.DESC_TIPO_CONTRATTO AS DES_TIPO_CONTRATTO_OLD
  , CASE WHEN #il campo COD_CONTRATTO_STORNATO ha sostituito OFF.COD_OFFERTA_PFISSE per le offerte TTFSA perchè serve 
              #per recuperare il tipo_contratto corretto per i calcoli degli storni
          off.cod_offerta like 'S-%' AND TC.DESC_TIPO_CONTRATTO not like '%TTFSA%' THEN CAST(OFF.COD_OFFERTA_PFISSE AS STRING)
          WHEN 
          off.cod_offerta like 'S-%' AND TC.DESC_TIPO_CONTRATTO LIKE '%TTFSA%' THEN CAST(OFF.COD_CONTRATTO_STORNATO AS STRING)
          when
          off.cod_offerta like '%F%' AND TC.DESC_TIPO_CONTRATTO NOT LIKE '%TTFSA%' THEN CAST(OFF.COD_OFFERTA_PFISSE AS STRING)
          WHEN
          off.COD_OFFERTA LIKE '%F%' AND TC.DESC_TIPO_CONTRATTO LIKE '%TTFSA%' THEN CAST(OFF.COD_OFFERTA_PFISSE AS STRING)
          ELSE NULL
          end AS OFFERTA_MADRE
          
  , case when
            off.cod_offerta like 'S-%' AND TC.DESC_TIPO_CONTRATTO not like '%TTFSA%' AND OFF.COD_OFFERTA NOT LIKE '%PPA%' then off.COD_CONTRATTO_STORNATO
           when 
            off.cod_offerta like 'S-%' AND (TC.DESC_TIPO_CONTRATTO LIKE '%TTFSA%' OR off.cod_offerta like '%PPA%') THEN SPLIT(off.COD_CONTRATTO_STORNATO, 'F')[SAFE_OFFSET(0)]
           when
            off.cod_offerta like '%F%' AND TC.DESC_TIPO_CONTRATTO NOT LIKE '%TTFSA%' AND OFF.COD_OFFERTA NOT LIKE '%PPA%' THEN off.CONTRATTO_OLD
           WHEN
            (off.COD_OFFERTA LIKE '%F%' AND TC.DESC_TIPO_CONTRATTO LIKE '%TTFSA%') OR (off.cod_offerta like '%PPA%' AND OFF.COD_OFFERTA NOT LIKE 'S-%') THEN SPLIT(off.CONTRATTO_OLD, 'F')[SAFE_OFFSET(0)]
           ELSE NULL END AS OFFERTA_STORNO_FIXING

  , off.DES_BONUS_LIBERO AS NOTE
  , '' AS PIVA_OFFERTABILE
  , '' AS CF_OFFERTABILE
  , '' AS PIVA_TITOLARE

from `a2a-labrrclab-prd.L0.DAR_MARGINI_GECOOFFERTE` off
inner join `a2a-labrrclab-prd.L0.DAR_MARGINI_GECOOFFERTEDETTAGLIO` off_dett
  on CAST(off.ID_OFFERTA AS STRING) = cast(off_dett.COD_OFFERTA as string)
inner join `a2a-dataplatform-prd.DP_LAB.GECO_TARIFFE` tariffe on off.COD_TARIFFA = tariffe.ID_TARIFFA
LEFT JOIN `a2a-labrrclab-prd.L0.DAR_MARGINI_LISTINI_SPECIALI` lsp
  ON off.ID_OFFERTA = lsp.ID_OFFERTA AND DATE(off_dett.DATA_VOLUME) = DATE(lsp.DATA_VOLUME)
left join `a2a-dataplatform-prd.DP_LAB.GECO_TIPO_LISTINO` gtl
  on cast(off.cod_listino as string)=cast(gtl.ID_TIPO_LISTINO as string)
LEFT JOIN `a2a-labrrclab-prd.L0.DAR_MARGINI_Trova_tensione_prevalente` TP 
  ON TP.RAGIONE_SOCIALE=off.RAGIONE_SOCIALE AND TP.DATA_DELIVERY=off_dett.DATA_VOLUME
LEFT JOIN (SELECT DISTINCT RAGIONE_SOCIALE, TENSIONE FROM `a2a-labrrclab-prd.L0.DAR_MARGINI_Trova_tensione_prevalente` QUALIFY ROW_NUMBER() OVER(PARTITION BY RAGIONE_SOCIALE ORDER BY TENSIONE DESC)=1) AS TP1
  ON TP1.RAGIONE_SOCIALE=off.RAGIONE_SOCIALE
LEFT JOIN (
  SELECT
    c.COD_TENSIONE,
    t.SIGLA,
    c.VALID_FROM,
    c.VALID_TO,
    c.COEFF
  FROM
    `a2a-dataplatform-prd.DP_LAB.GECO_COEFF_CONV_TENSIONE` c
  LEFT JOIN
    `a2a-dataplatform-prd.DP_LAB.GECO_TIPO_TENSIONE` t
  ON
    c.COD_TENSIONE = t.ID_TENSIONE) AS tens
ON
  COALESCE(OFF.COD_TENSIONE, TP.TENSIONE_DATA_DELIVERY, TP1.TENSIONE, 4.0) = tens.COD_TENSIONE
  AND DATE(COALESCE(TIMESTAMP(off_dett.DATA_COPERTURA), TIMESTAMP(lsp.rec_date))) BETWEEN DATE(tens.VALID_FROM)
  AND DATE(tens.VALID_TO)
LEFT JOIN `a2a-labrrc-prd.L0.TRANS_INDICE` tra
  ON tariffe.tariffa = tra.INDICE_DA_TRANSCODIFICARE
LEFT JOIN `a2a-dataplatform-prd.DP_LAB.GECO_TIPO_CONTRATTO` TC
  ON TC.ID_TIPO_CONTRATTO=off.COD_TIPO_CONTRATTO
LEFT JOIN `a2a-dataplatform-prd.DP_LAB.GECO_TIPO_CONTRATTO` TC1
  ON TC1.ID_TIPO_CONTRATTO=off.COD_TIPO_CONTRATTO_OLD
LEFT JOIN `a2a-labrrclab-prd.L0.DAR_MARGINI_TRANSCODIFICA_TIPO_CONTRATTO` TC2
  ON TC.DESC_TIPO_CONTRATTO = TC2.string_field_0
where 
  (off.COD_STATO in (5) OR (off.COD_STATO in (8) AND lsp.ID is not null))
  AND off_dett.DATA_VOLUME>='2024-01-01' ),



#Inserimento informazioni prese da altre sorgenti
#B2Be
GECO_CORE_B2Be AS(
SELECT 
    GECO_CORE.ID_OFFERTA
  , GECO_CORE.ID_DETTAGLIO
  , GECO_CORE.FLG_PUBBLICATO_S_N
  , GECO_CORE.COD_OFFERTA
  , GECO_CORE.COD_OPPORTUNITY_CORRETTO
  , GECO_CORE.PDP
  , GECO_CORE.NUMERO_PDP
  , GECO_CORE.CABINA_REMI
  , GECO_CORE.FLG_ENVE_S_N_I
  , GECO_CORE.CASE_ADDENDUM_ENVE
  , GECO_CORE.DATA_COPERTURA
  , GECO_CORE.COMMODITY_G_E
  , GECO_CORE.DATA_CARICAMENTO
  , GECO_CORE.DATA_INIZIO_OFFERTA
  , GECO_CORE.DATA_FINE_OFFERTA
  , GECO_CORE.DATA_INIZIO_COPERTURA
  , GECO_CORE.DATA_FINE_COPERTURA
  , GECO_CORE.TIPO_CONTRATTO
  , GECO_CORE.DES_TIPO_CONTRATTO
  , GECO_CORE.DES_TIPO_CONTRATTO_SINTESI
  , GECO_CORE.PROFILO_MONO_BIO_POP_FASCE
  , GECO_CORE.TENSIONE
  , GECO_CORE.DES_TENSIONE
  , GECO_CORE.INDICE
  , IF(COALESCE(IF(pra.TIPOLOGIA_PDR='0' or pra.TIPOLOGIA_PDR='1','DOM',
      IF(pra.TIPOLOGIA_PDR='2','AU',
      IF(pra.TIPOLOGIA_PDR='3','IP',null))),
      GECO_CORE.TIPOLOGIA_USO) is null, "AU", COALESCE(IF(pra.TIPOLOGIA_PDR='0' or pra.TIPOLOGIA_PDR='1','DOM',
      IF(pra.TIPOLOGIA_PDR='2','AU',
      IF(pra.TIPOLOGIA_PDR='3','IP',null))),
      GECO_CORE.TIPOLOGIA_USO)) AS TIPOLOGIA_USO
  , GECO_CORE.VENDITORE
  , GECO_CORE.COD_VENDITORE
  , GECO_CORE.DATA_DELIVERY
  , GECO_CORE.VOLUME_COPERTO_MC_MWH
  , GECO_CORE.VOLUME_COPERTO_F1_MWH
  , GECO_CORE.VOLUME_COPERTO_F2_MWH
  , GECO_CORE.VOLUME_COPERTO_F3_MWH
  , GECO_CORE.VOLUME_COPERTO_P_MWH #DA AGGIORNARE SE E QUANDO SI POTRANNO FARE LE COPERTURE PER POP
  , GECO_CORE.VOLUME_COPERTO_OP_MWH #DA AGGIORNARE SE E QUANDO SI POTRANNO FARE LE COPERTURE PER POP
  , GECO_CORE.VOLUME_NETTO_COPERTO_MC_MWH
  , GECO_CORE.VOLUME_NETTO_COPERTO_F1_MWH
  , GECO_CORE.VOLUME_NETTO_COPERTO_F2_MWH
  , GECO_CORE.VOLUME_NETTO_COPERTO_F3_MWH
  , GECO_CORE.VOLUME_NETTO_COPERTO_P_MWH
  , GECO_CORE.VOLUME_NETTO_COPERTO_OP_MWH
  , GECO_CORE.VOLUME_PERDITE_MC_MWH
  , GECO_CORE.VOLUME_PERDITE_F1_MWH
  , GECO_CORE.VOLUME_PERDITE_F2_MWH
  , GECO_CORE.VOLUME_PERDITE_F3_MWH
  , GECO_CORE.VOLUME_PERDITE_P_MWH
  , GECO_CORE.VOLUME_PERDITE_OP_MWH
  , GECO_CORE.VOLUME_ENVE_MWH
  , GECO_CORE.FLG_LISTINO_MP_STD_GC10_SPE 
  , GECO_CORE.SISTEMA
  , GECO_CORE.CONTRATTO_OLD
  , GECO_CORE.COD_TIPO_CONTRATTO_OLD
  , GECO_CORE.DES_TIPO_CONTRATTO_OLD
  , GECO_CORE.OFFERTA_MADRE
  --Inserito qui CONTRATTO STORNATA
  , GECO_CORE.OFFERTA_STORNO_FIXING
  , GECO_CORE.NOTE
  , GECO_CORE.PIVA_OFFERTABILE
  , GECO_CORE.CF_OFFERTABILE
  , GECO_CORE.PIVA_TITOLARE

 -- , pr.codice_opportunity
FROM (SELECT * FROM GECO_CORE WHERE GECO_CORE.SISTEMA = "B2Be" OR GECO_CORE.SISTEMA = "SMS") as GECO_CORE
LEFT JOIN (SELECT DISTINCT CODICE_OFFERTA, expiry_ts, FK_STATI_PRATICHE, MIN(TIPOLOGIA_PDR) as TIPOLOGIA_PDR, COUNT(DISTINCT FK_PUNTI_DI_FORNITURA) AS NUMERO_PDP FROM `a2a-labrrclab-prd.L0.DAR_PraticheCompletaFiltrata_tabella` WHERE TIPOLOGIA_PDR is not null GROUP BY CODICE_OFFERTA, expiry_ts, FK_STATI_PRATICHE) as pra 
on pra.CODICE_OFFERTA = GECO_CORE.COD_OFFERTA
Where pra.expiry_ts is null and (GECO_CORE.SISTEMA = "B2Be" OR GECO_CORE.SISTEMA = "SMS") 
),

#CRME
GECO_CORE_CRMe AS(
SELECT 
    GECO_CORE.ID_OFFERTA
  , GECO_CORE.ID_DETTAGLIO
  , GECO_CORE.FLG_PUBBLICATO_S_N
  , GECO_CORE.COD_OFFERTA
  , GECO_CORE.COD_OPPORTUNITY_CORRETTO
  , GECO_CORE.PDP
  , GECO_CORE.NUMERO_PDP
  , GECO_CORE.CABINA_REMI
  , GECO_CORE.FLG_ENVE_S_N_I
  , GECO_CORE.CASE_ADDENDUM_ENVE
  , GECO_CORE.DATA_COPERTURA
  , GECO_CORE.COMMODITY_G_E
  , GECO_CORE.DATA_CARICAMENTO
  , GECO_CORE.DATA_INIZIO_OFFERTA
  , GECO_CORE.DATA_FINE_OFFERTA
  , GECO_CORE.DATA_INIZIO_COPERTURA
  , GECO_CORE.DATA_FINE_COPERTURA
  , GECO_CORE.TIPO_CONTRATTO
  , GECO_CORE.DES_TIPO_CONTRATTO
  , GECO_CORE.DES_TIPO_CONTRATTO_SINTESI
  , GECO_CORE.PROFILO_MONO_BIO_POP_FASCE
  , GECO_CORE.TENSIONE
  , GECO_CORE.DES_TENSIONE
  , GECO_CORE.INDICE
  , IF(COALESCE(IF(pra.TIPOLOGIA_PDR='0' or pra.TIPOLOGIA_PDR='1','DOM',
      IF(pra.TIPOLOGIA_PDR='2','AU',
      IF(pra.TIPOLOGIA_PDR='3','IP',null))),
      GECO_CORE.TIPOLOGIA_USO) is null, "AU",COALESCE(IF(pra.TIPOLOGIA_PDR='0' or pra.TIPOLOGIA_PDR='1','DOM',
      IF(pra.TIPOLOGIA_PDR='2','AU',
      IF(pra.TIPOLOGIA_PDR='3','IP',null))),
      GECO_CORE.TIPOLOGIA_USO)) AS TIPOLOGIA_USO
  , GECO_CORE.VENDITORE
  , GECO_CORE.COD_VENDITORE
  , GECO_CORE.DATA_DELIVERY
  , GECO_CORE.VOLUME_COPERTO_MC_MWH
  , GECO_CORE.VOLUME_COPERTO_F1_MWH
  , GECO_CORE.VOLUME_COPERTO_F2_MWH
  , GECO_CORE.VOLUME_COPERTO_F3_MWH
  , GECO_CORE.VOLUME_COPERTO_P_MWH #DA AGGIORNARE SE E QUANDO SI POTRANNO FARE LE COPERTURE PER POP
  , GECO_CORE.VOLUME_COPERTO_OP_MWH #DA AGGIORNARE SE E QUANDO SI POTRANNO FARE LE COPERTURE PER POP
  , GECO_CORE.VOLUME_NETTO_COPERTO_MC_MWH
  , GECO_CORE.VOLUME_NETTO_COPERTO_F1_MWH
  , GECO_CORE.VOLUME_NETTO_COPERTO_F2_MWH
  , GECO_CORE.VOLUME_NETTO_COPERTO_F3_MWH
  , GECO_CORE.VOLUME_NETTO_COPERTO_P_MWH
  , GECO_CORE.VOLUME_NETTO_COPERTO_OP_MWH
  , GECO_CORE.VOLUME_PERDITE_MC_MWH
  , GECO_CORE.VOLUME_PERDITE_F1_MWH
  , GECO_CORE.VOLUME_PERDITE_F2_MWH
  , GECO_CORE.VOLUME_PERDITE_F3_MWH
  , GECO_CORE.VOLUME_PERDITE_P_MWH
  , GECO_CORE.VOLUME_PERDITE_OP_MWH
  , GECO_CORE.VOLUME_ENVE_MWH
  , GECO_CORE.FLG_LISTINO_MP_STD_GC10_SPE
  , GECO_CORE.SISTEMA
  , GECO_CORE.CONTRATTO_OLD
  , GECO_CORE.COD_TIPO_CONTRATTO_OLD
  , GECO_CORE.DES_TIPO_CONTRATTO_OLD
  ,GECO_CORE.OFFERTA_MADRE
  --Inserito qui CONTRATTO STORNATA
  , GECO_CORE.OFFERTA_STORNO_FIXING
  , GECO_CORE.NOTE
  , GECO_CORE.PIVA_OFFERTABILE
  , GECO_CORE.CF_OFFERTABILE
  , GECO_CORE.PIVA_TITOLARE
 -- , pr.codice_opportunity
FROM (SELECT * FROM GECO_CORE WHERE GECO_CORE.SISTEMA = "SFA") as GECO_CORE
LEFT JOIN (SELECT DISTINCT CODICE_OPPORTUNITY, expiry_ts, FK_STATI_PRATICHE, MIN(TIPOLOGIA_PDR) as TIPOLOGIA_PDR, COUNT(DISTINCT FK_PUNTI_DI_FORNITURA) AS NUMERO_PDP  FROM `a2a-labrrclab-prd.L0.DAR_PraticheCompletaFiltrata_tabella` WHERE TIPOLOGIA_PDR is not null and FK_STATI_PRATICHE in (3, 4, 12, 41, 43, 60, 62, 81, 86) GROUP BY CODICE_OPPORTUNITY, expiry_ts, FK_STATI_PRATICHE) as pra 
on pra.CODICE_OPPORTUNITY = GECO_CORE.COD_OPPORTUNITY_CORRETTO
Where pra.expiry_ts is null and GECO_CORE.SISTEMA = "SFA"
),


GECO_CORE_ALTRI_SISTEMI AS (
  SELECT *
  FROM GECO_CORE
  WHERE GECO_CORE.SISTEMA = "EXTRA SISTEMA" OR GECO_CORE.SISTEMA = "MMK"
)

select distinct * from GECO_CORE_B2Be
union distinct
select distinct * from GECO_CORE_CRMe
union distinct
select distinct * from GECO_CORE_ALTRI_SISTEMI
